defaults:
  - data: muscle_us
  - task: gaussian_diff_seg
  # config below overwrites the values above
  # https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order/
  - _self_

debug: False
seed: 0
half_precision: True

optimizer:
  name: "adamw"
  kwargs:
    b1: 0.9
    b2: 0.999
    weight_decay: 1e-08
  grad_norm: 1.0
  lr_schedule:
    warmup_steps: 100
    decay_steps: 10_000
    init_value: 1e-05
    peak_value: 8e-04
    end_value: 5e-05

logging:
  root_dir:
  log_freq: 10
  save_freq: 500
  wandb:
    project: imgx
    entity: wandb_entity
