name: "segmentation"

model:
  _target_: imgx.model.Unet
  remat: True
  num_spatial_dims: 3
  patch_size: MISSING # data dependent, will be set after loading config
  scale_factor: MISSING # data dependent, will be set after loading config
  num_res_blocks: 2
  num_channels: [32, 64, 128, 256]
  out_channels: MISSING # data dependent, will be set after loading config
  num_heads: 8
  widening_factor: 4
  num_transform_layers: 1
  dropout: 0.1

loss:
  dice: 1.0
  cross_entropy: 0.0
  focal: 1.0

early_stopping: # used on validation set
  metric: "mean_binary_dice_score_without_background"
  mode: "max"
  min_delta: 0.0001
  patience: 10
