name: imgx
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.3.1
  - pip:
      - tensorflow-macos==2.14.0
      - tensorflow-metal==1.1.0
      - jax==0.4.20
      - jaxlib==0.4.20
      - -r requirements.txt
