name: imgx
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.0.1
  - pip:
      - tensorflow-macos==2.13.0
      - tensorflow-metal==1.0.1
      - jax==0.4.14
      - jaxlib==0.4.14
      - -r requirements.txt
