name: "diffusion_segmentation"

recycling:
  use: True
  # max means the previous step is num_timesteps - 1
  # next means the previous step is min(t+1, num_timesteps - 1)
  prev_step: "max" # max or next
  reverse_step: False
  aux_loss: False

self_conditioning:
  use: False
  probability: 0.5
  prev_step: "next" # same or next
  aux_loss: False

uniform_time_sampling: False # False for importance sampling

diffusion:
  _target_: imgx.diffusion.GaussianDiffusionSegmentation
  num_timesteps: 5
  num_timesteps_beta: 1001
  beta_schedule: "LINEAR" # LINEAR, QUADRADIC, COSINE, WARMUP10, WARMUP50
  beta_start: 0.0001
  beta_end: 0.02
  model_out_type: "X_START" # X_START, NOISE
  model_var_type: "FIXED_SMALL" # FIXED_SMALL, FIXED_LARGE, LEARNED, LEARNED_RANGE

sampler:
  name: "DDPM" # DDPM, DDIM
  num_inference_timesteps: 5

model:
  _target_: imgx.model.Unet
  remat: True
  num_spatial_dims: 3
  patch_size: 2
  num_channels: [32, 64, 128, 256]
  out_channels: MISSING # will be set after loading config
