name: unit-test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      matrix:
        group: [1, 2, 3, 4]
        python-version: ["3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            docker/environment.yml
            docker/environment_mac_m1.yml
            docker/Dockerfile
            docker/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow-cpu==2.12.0
          pip install jax==0.4.20
          pip install jaxlib==0.4.20
          pip install -r docker/requirements.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest --splits 4 --group ${{ matrix.group }} --randomly-seed=0 -k "not slow and not integration"
