name: unit-test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            docker/environment.yml
            docker/environment_mac_m1.yml
            docker/Dockerfile
            docker/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow-cpu==2.11.0
          pip install jax==0.4.1
          pip install jaxlib==0.4.1
          pip install -r docker/requirements.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest tests/unit
